
name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      working-directory: ./gemma_chatbot
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install ruff

    - name: Lint with ruff
      working-directory: ./gemma_chatbot
      run: |
        ruff check --output-format=github .
    

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set Docker tags to lowercase
      id: tags
      run: echo "repo_lowercase=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./gemma_chatbot
        push: true
        tags: ghcr.io/${{ env.repo_lowercase }}:${{ github.sha }}
